export const projects = [
    {
        id: 1,
        title: "Dharmodaya Sabha Bihar",
        description: "Location: Balkumari, Laliptur </br> Land Area: 1545 sqft </br> Plinth Area: 1200 sqft",
        image: "assets/project-images/1/main.jpg",
        gallery: [
			"../assets/project-images/1/gallery1.jpg",
			"../assets/project-images/1/gallery2.jpg",
			"../assets/project-images/1/gallery3.jpg",
			"../assets/project-images/1/1.jpg",
			"../assets/project-images/1/2.jpg",
			"../assets/project-images/1/3.jpg",
			"../assets/project-images/1/4.jpg",
			"../assets/project-images/1/5.jpg",
			"../assets/project-images/1/6.jpg",
			"../assets/project-images/1/7.jpg",
			"../assets/project-images/1/8.jpg",
			"../assets/project-images/1/9.jpg",
			"../assets/project-images/1/10.jpg",
			"../assets/project-images/1/11.jpg",
			"../assets/project-images/1/12.jpg",
			"../assets/project-images/1/13.jpg",
			"../assets/project-images/1/14.jpg",
			"../assets/project-images/1/15.jpg",
			"../assets/project-images/1/16.jpg",
			"../assets/project-images/1/16.jpg",
			"../assets/project-images/1/17.jpg",
			"../assets/project-images/1/18.jpg",
			"../assets/project-images/1/19.jpg",
			"../assets/project-images/1/20.jpg",
			"../assets/project-images/1/21.jpg",
			"../assets/project-images/1/22.jpg",
			"../assets/project-images/1/23.jpg",
			"../assets/project-images/1/24.jpg",
			"../assets/project-images/1/25.jpg",
			"../assets/project-images/1/26.jpg",
			"../assets/project-images/1/27.jpg",
			"../assets/project-images/1/28.jpg",
			"../assets/project-images/1/29.jpg",
			"../assets/project-images/1/30.jpg",
			"../assets/project-images/1/31.jpg",
			"../assets/project-images/1/32.jpg",
			"../assets/project-images/1/33.jpg",
			"../assets/project-images/1/34.jpg",
			"../assets/project-images/1/35.jpg",
			"../assets/project-images/1/36.jpg",
			"../assets/project-images/1/37.jpg",
			"../assets/project-images/1/28.jpg",
			"../assets/project-images/1/39.jpg",
			"../assets/project-images/1/40.jpg",
			"../assets/project-images/1/42.jpg",
			"../assets/project-images/1/43.jpg",
			"../assets/project-images/1/44.jpg"
        ]
    },
    {
		id: 2,
		title: "Khokana Residential House",
		description: "Location: Khokana, Laliptur </br> Land Area: 1545 sqft </br> Plinth Area: 1200 sqft",
		image: "assets/project-images/2/main.jpg",
		gallery: [
			"../assets/project-images/2/gallery1.jpg",
			"../assets/project-images/2/gallery2.jpg",
			"../assets/project-images/2/gallery3.jpg",
			"../assets/project-images/2/gallery4.jpg",
			"../assets/project-images/2/1.jpg",
			"../assets/project-images/2/3.jpg",
			"../assets/project-images/2/4.jpg",
			"../assets/project-images/2/5.jpg",
			"../assets/project-images/2/2.jpg",
			"../assets/project-images/2/6.jpg",
			"../assets/project-images/2/7.jpg",
			"../assets/project-images/2/8.jpg",
			"../assets/project-images/2/9.jpg",
			"../assets/project-images/2/10.jpg",
			"../assets/project-images/2/11.jpg",
			"../assets/project-images/2/12.jpg",
			// "../assets/project-images/2/13.jpg",
			// "../assets/project-images/2/14.jpg",
			"../assets/project-images/2/15.jpg",
			"../assets/project-images/2/16.jpg",
			"../assets/project-images/2/17.jpg",
			"../assets/project-images/2/18.jpg",
			"../assets/project-images/2/19.jpg",
			"../assets/project-images/2/20.jpg",
			"../assets/project-images/2/21.jpg",
			"../assets/project-images/2/22.jpg",
			"../assets/project-images/2/23.jpg",
			"../assets/project-images/2/24.jpg",
			// "../assets/project-images/2/25.jpg",
			"../assets/project-images/2/26.jpg",
			"../assets/project-images/2/27.jpg",
			"../assets/project-images/2/29.jpg",
			"../assets/project-images/2/30.jpg",
			"../assets/project-images/2/31.jpg",
			// "../assets/project-images/2/32.jpg",
			"../assets/project-images/2/33.jpg",
			"../assets/project-images/2/34.jpg",
		]
    },
    {
		id: 3,
		title: "Pet Line Renovation",
		description: "Location: Bottler's Nepal Pvt. Ltd., Balaju ",
		image: "assets/project-images/3/main.jpg",
		gallery: [
			"../assets/project-images/3/1.jpg",
			"../assets/project-images/3/2.jpg",
			"../assets/project-images/3/3.jpg",
			"../assets/project-images/3/4.jpg",
			"../assets/project-images/3/5.jpg",
			"../assets/project-images/3/6.jpg",
			"../assets/project-images/3/7.jpg",
			"../assets/project-images/3/8.jpg",
			"../assets/project-images/3/9.jpg",
			"../assets/project-images/3/10.jpg",
			"../assets/project-images/3/11.jpg",
			"../assets/project-images/3/12.jpg",
			"../assets/project-images/3/13.jpg",
			"../assets/project-images/3/14.jpg",
			"../assets/project-images/3/15.jpg",
			"../assets/project-images/3/16.jpg",
			"../assets/project-images/3/17.jpg",
			"../assets/project-images/3/18.jpg",
			"../assets/project-images/3/19.jpg",
			"../assets/project-images/3/20.jpg",
			"../assets/project-images/3/21.jpg",
			"../assets/project-images/3/22.jpg",
			"../assets/project-images/3/23.jpg",
			"../assets/project-images/3/24.jpg",
			"../assets/project-images/3/25.jpg",
			"../assets/project-images/3/26.jpg",
			"../assets/project-images/3/27.jpg",
			"../assets/project-images/3/28.jpg",
			"../assets/project-images/3/29.jpg",
			"../assets/project-images/3/30.jpg",
			"../assets/project-images/3/31.jpg",
			"../assets/project-images/3/32.jpg",
			"../assets/project-images/3/33.jpg",
			"../assets/project-images/3/34.jpg",
			"../assets/project-images/3/35.jpg",
			"../assets/project-images/3/36.jpg",
			"../assets/project-images/3/37.jpg",
			"../assets/project-images/3/38.jpg",
			"../assets/project-images/3/39.jpg",
			"../assets/project-images/3/40.jpg",
			"../assets/project-images/3/41.jpg",
			"../assets/project-images/3/42.jpg",
			"../assets/project-images/3/43.jpg",
			"../assets/project-images/3/44.jpg",
			"../assets/project-images/3/45.jpg",
			"../assets/project-images/3/46.jpg",
			"../assets/project-images/3/47.jpg",
			"../assets/project-images/3/48.jpg",
			"../assets/project-images/3/49.jpg",
			"../assets/project-images/3/50.jpg",
			"../assets/project-images/3/51.jpg",
			"../assets/project-images/3/52.jpg",
			"../assets/project-images/3/53.jpg",
			"../assets/project-images/3/54.jpg",
			"../assets/project-images/3/55.jpg",
		]
    }
  ];