export const projects = [
    {
        id: 1,
        title: "Dharmodaya Sabha Bihar",
        description: "Location: Balkumari, Laliptur </br> Land Area: 3733.95 sqft [0-11-0-0] </br> Plinth Area: 1429.29 sqft",
        image: "assets/project-images/1/main.jpg",
        gallery: [
			"assets/project-images/1/gallery1.jpg",
			"assets/project-images/1/gallery2.jpg",
			"assets/project-images/1/gallery3.jpg",
			"assets/project-images/1/3d1.jpg",
			"assets/project-images/1/3d2.jpg",
			"assets/project-images/1/3d3.jpg",
			"assets/project-images/1/3d4.jpg",
			"assets/project-images/1/3d5.jpg",
			"assets/project-images/1/3d6.jpg",
			"assets/project-images/1/3d7.jpg",
			"assets/project-images/1/3d8.jpg",
			"assets/project-images/1/3d9.jpg",
			"assets/project-images/1/3d10.jpg",
			"assets/project-images/1/3d11.jpg",
			"assets/project-images/1/1.jpg",
			"assets/project-images/1/2.jpg",
			"assets/project-images/1/3.jpg",
			"assets/project-images/1/4.jpg",
			"assets/project-images/1/5.jpg",
			"assets/project-images/1/6.jpg",
			"assets/project-images/1/7.jpg",
			"assets/project-images/1/8.jpg",
			"assets/project-images/1/9.jpg",
			"assets/project-images/1/10.jpg",
			"assets/project-images/1/11.jpg",
			"assets/project-images/1/12.jpg",
			"assets/project-images/1/13.jpg",
			"assets/project-images/1/14.jpg",
			"assets/project-images/1/14a.jpg",
			"assets/project-images/1/14b.jpg",
			"assets/project-images/1/15.jpg",
			"assets/project-images/1/16.jpg",
			"assets/project-images/1/16.jpg",
			"assets/project-images/1/17.jpg",
			"assets/project-images/1/18.jpg",
			"assets/project-images/1/19.jpg",
			"assets/project-images/1/20.jpg",
			"assets/project-images/1/21.jpg",
			"assets/project-images/1/22.jpg",
			"assets/project-images/1/23.jpg",
			"assets/project-images/1/24.jpg",
			"assets/project-images/1/25.jpg",
			"assets/project-images/1/26.jpg",
			"assets/project-images/1/27.jpg",
			"assets/project-images/1/28.jpg",
			"assets/project-images/1/29.jpg",
			"assets/project-images/1/30.jpg",
			"assets/project-images/1/31.jpg",
			"assets/project-images/1/32.jpg",
			"assets/project-images/1/33.jpg",
			"assets/project-images/1/34.jpg",
			"assets/project-images/1/35.jpg",
			"assets/project-images/1/36.jpg",
			"assets/project-images/1/37.jpg",
			"assets/project-images/1/28.jpg",
			"assets/project-images/1/39.jpg",
			"assets/project-images/1/40.jpg",
			"assets/project-images/1/42.jpg",
			"assets/project-images/1/43.jpg",
			"assets/project-images/1/44.jpg",
			"assets/project-images/1/45.jpg",
			"assets/project-images/1/46.jpg",
			"assets/project-images/1/47.jpg",
			"assets/project-images/1/455.jpg",
			"assets/project-images/1/466.jpg",
			"assets/project-images/1/48.jpg",
			"assets/project-images/1/49.jpg",
			"assets/project-images/1/50.jpg",
			"assets/project-images/1/51.jpg",
			"assets/project-images/1/52.jpg",
			"assets/project-images/1/53.jpg",
			"assets/project-images/1/54.jpg",
			"assets/project-images/1/55.jpg",
			"assets/project-images/1/57.jpg",
			"assets/project-images/1/58.jpg",
			"assets/project-images/1/59.jpg",
			"assets/project-images/1/60.jpg",
			"assets/project-images/1/62.jpg",
			"assets/project-images/1/63.jpg",
			"assets/project-images/1/64.jpg",
			"assets/project-images/1/65.jpg",
			"assets/project-images/1/66.jpg",
			"assets/project-images/1/67.jpg",
			"assets/project-images/1/68.jpg",
			"assets/project-images/1/69.jpg",
			"assets/project-images/1/70.jpg",
			"assets/project-images/1/71.jpg",
			"assets/project-images/1/72.jpg",
        ]
    },
    {
		id: 2,
		title: "Khokana Residential House",
		description: "Location: Khokana, Laliptur </br> Land Area: 1540.12 sqft [0-4-1-3.98]</br> Plinth Area: 752.51 sqft",
		image: "assets/project-images/2/main.jpg",
		gallery: [
			"assets/project-images/2/gallery1.jpg",
			"assets/project-images/2/gallery2.jpg",
			"assets/project-images/2/gallery3.jpg",
			"assets/project-images/2/gallery4.jpg",
			"assets/project-images/2/1.jpg",
			"assets/project-images/2/1a.jpg",
			"assets/project-images/2/3.jpg",
			"assets/project-images/2/3a.jpg",
			"assets/project-images/2/3b.jpg",
			"assets/project-images/2/3c.jpg",
			"assets/project-images/2/3d.jpg",
			"assets/project-images/2/3e.jpg",
			"assets/project-images/2/3f.jpg",
			"assets/project-images/2/4.jpg",
			"assets/project-images/2/5.jpg",
			"assets/project-images/2/2.jpg",
			"assets/project-images/2/6.jpg",
			"assets/project-images/2/7.jpg",
			"assets/project-images/2/8.jpg",
			"assets/project-images/2/9.jpg",
			"assets/project-images/2/10.jpg",
			"assets/project-images/2/11.jpg",
			"assets/project-images/2/12.jpg",
			// "assets/project-images/2/13.jpg",
			// "assets/project-images/2/14.jpg",
			"assets/project-images/2/15.jpg",
			"assets/project-images/2/16.jpg",
			"assets/project-images/2/17.jpg",
			"assets/project-images/2/18.jpg",
			"assets/project-images/2/19.jpg",
			"assets/project-images/2/20.jpg",
			"assets/project-images/2/21.jpg",
			"assets/project-images/2/22.jpg",
			"assets/project-images/2/23.jpg",
			"assets/project-images/2/24.jpg",
			// "assets/project-images/2/25.jpg",
			"assets/project-images/2/26.jpg",
			"assets/project-images/2/27.jpg",
			"assets/project-images/2/29.jpg",
			"assets/project-images/2/30.jpg",
			"assets/project-images/2/31.jpg",
			// "assets/project-images/2/32.jpg",
			"assets/project-images/2/33.jpg",
			"assets/project-images/2/34.jpg",
		]
    },
    {
		id: 3,
		title: "Pet Line Renovation",
		description: "Location: Bottler's Nepal Pvt. Ltd., Balaju ",
		image: "assets/project-images/3/main.jpg",
		gallery: [
			"assets/project-images/3/1.jpg",
			"assets/project-images/3/2.jpg",
			"assets/project-images/3/3.jpg",
			"assets/project-images/3/4.jpg",
			"assets/project-images/3/5.jpg",
			"assets/project-images/3/6.jpg",
			"assets/project-images/3/7.jpg",
			"assets/project-images/3/8.jpg",
			"assets/project-images/3/9.jpg",
			"assets/project-images/3/10.jpg",
			"assets/project-images/3/11.jpg",
			"assets/project-images/3/12.jpg",
			"assets/project-images/3/13.jpg",
			"assets/project-images/3/14.jpg",
			"assets/project-images/3/15.jpg",
			"assets/project-images/3/16.jpg",
			"assets/project-images/3/17.jpg",
			"assets/project-images/3/18.jpg",
			"assets/project-images/3/19.jpg",
			"assets/project-images/3/20.jpg",
			"assets/project-images/3/21.jpg",
			"assets/project-images/3/22.jpg",
			"assets/project-images/3/23.jpg",
			"assets/project-images/3/24.jpg",
			"assets/project-images/3/25.jpg",
			"assets/project-images/3/26.jpg",
			"assets/project-images/3/27.jpg",
			"assets/project-images/3/28.jpg",
			"assets/project-images/3/29.jpg",
			"assets/project-images/3/30.jpg",
			"assets/project-images/3/31.jpg",
			"assets/project-images/3/32.jpg",
			"assets/project-images/3/33.jpg",
			"assets/project-images/3/34.jpg",
			"assets/project-images/3/35.jpg",
			"assets/project-images/3/36.jpg",
			"assets/project-images/3/37.jpg",
			"assets/project-images/3/38.jpg",
			"assets/project-images/3/39.jpg",
			"assets/project-images/3/40.jpg",
			"assets/project-images/3/41.jpg",
			"assets/project-images/3/42.jpg",
			"assets/project-images/3/43.jpg",
			"assets/project-images/3/44.jpg",
			"assets/project-images/3/45.jpg",
			"assets/project-images/3/46.jpg",
			"assets/project-images/3/47.jpg",
			"assets/project-images/3/48.jpg",
			"assets/project-images/3/49.jpg",
			"assets/project-images/3/50.jpg",
			"assets/project-images/3/51.jpg",
			"assets/project-images/3/52.jpg",
			"assets/project-images/3/53.jpg",
			"assets/project-images/3/54.jpg",
			"assets/project-images/3/55.jpg",
		]
    },
	{
		id: 4,
		title: "Enscape Stay Renovation",
		description: "Location: Chundevi Marg, Kathmandu ",
		image: "assets/project-images/4/main.jpg",
		gallery: [
			"assets/project-images/4/a.jpg",
			"assets/project-images/4/b.jpg",
			"assets/project-images/4/c.jpg",
			"assets/project-images/4/d.jpg",
			"assets/project-images/4/e.jpg",
			"assets/project-images/4/1.jpg",
			"assets/project-images/4/2.jpg",
			"assets/project-images/4/3.jpg",
			"assets/project-images/4/4.jpg",
			"assets/project-images/4/5.jpg",
			"assets/project-images/4/6.jpg",
			"assets/project-images/4/7.jpg",
			"assets/project-images/4/8.jpg",
			"assets/project-images/4/9.jpg",
			"assets/project-images/4/10.jpg",
			"assets/project-images/4/11.jpg",
			"assets/project-images/4/12.jpg",
			"assets/project-images/4/13.jpg",
		]
    },
	{
        id: 5,
        title: "Canteen Block Construction",
        description: "Location: Bottler's Nepal Terai Limited </br> Bharatpur, Chitwan",
        image: "assets/project-images/5/main.jpg",
        gallery: [
			"assets/project-images/5/1.jpg",
			"assets/project-images/5/2.jpg",
			"assets/project-images/5/3.jpg",
			"assets/project-images/5/4.jpg",
			"assets/project-images/5/5.jpg",
			"assets/project-images/5/6.jpg",
			"assets/project-images/5/7.jpg",
			"assets/project-images/5/7_1.jpg",
			"assets/project-images/5/8.jpg",
			"assets/project-images/5/9.jpg",
			"assets/project-images/5/10.jpg",
			"assets/project-images/5/10_1.jpg",
			"assets/project-images/5/11.jpg",
			"assets/project-images/5/12.jpg",
			"assets/project-images/5/13.jpg",
			"assets/project-images/5/14.jpg",
			"assets/project-images/5/14_1.jpg",
			"assets/project-images/5/15.jpg",
			"assets/project-images/5/15_1.jpg",
			"assets/project-images/5/15_2.jpg",
			"assets/project-images/5/16.jpg",
			"assets/project-images/5/16.jpg",
			"assets/project-images/5/17.jpg",
			"assets/project-images/5/18.jpg",
			"assets/project-images/5/19.jpg",
			"assets/project-images/5/20.jpg",
			"assets/project-images/5/21.jpg",
			"assets/project-images/5/22.jpg",
			"assets/project-images/5/23.jpg",
			"assets/project-images/5/24.jpg",
			"assets/project-images/5/25.jpg",
			"assets/project-images/5/26.jpg",
			"assets/project-images/5/27.jpg",
			"assets/project-images/5/28.jpg",
			"assets/project-images/5/29.jpg",
			"assets/project-images/5/30.jpg",
			"assets/project-images/5/31.jpg",
			"assets/project-images/5/32.jpg",
			"assets/project-images/5/33.jpg",
			"assets/project-images/5/34.jpg",
			"assets/project-images/5/36.jpg",
			"assets/project-images/5/37.jpg",
			"assets/project-images/5/38.jpg",
			"assets/project-images/5/39.jpg",
			"assets/project-images/5/40.jpg",
			"assets/project-images/5/41.jpg",
			"assets/project-images/5/42.jpg",
			"assets/project-images/5/43.jpg"
        ]
    },
	{
		id: 6,
		title: "Daraz Center PCC Floor and Block work",
		description: "Location: New Road, Kathmandu",
		image: "assets/project-images/6/main.jpg",
		gallery: [
			"assets/project-images/6/1.jpg",
			"assets/project-images/6/1_1.jpg",
			"assets/project-images/6/1_2.jpg",
			"assets/project-images/6/9.jpg",
			"assets/project-images/6/10.jpg",
			"assets/project-images/6/3.jpg",
			"assets/project-images/6/4.jpg",
			"assets/project-images/6/5.jpg",
			"assets/project-images/6/6.jpg",
			"assets/project-images/6/7.jpg",
			"assets/project-images/6/8.jpg",
			// "assets/project-images/6/11.jpg",
			"assets/project-images/6/12.jpg",
			"assets/project-images/6/13.jpg",
			"assets/project-images/6/14.jpg",
			"assets/project-images/6/15.jpg",
			"assets/project-images/6/16.jpg",
			"assets/project-images/6/final.jpg",
		]
    },
  ];